# filename: monitoring/grafana/provisioning/datasources/prometheus.yml
# purpose:  Auto-provision Prometheus as default datasource in Grafana.
# version:  1.0

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
